spring:
  data:
    mongodb:
      uri: mongodb+srv://CNJava:IE303M22@diamondjewelry.a5ssy.mongodb.net/diamondjewelry_db?retryWrites=true&w=majority
      auto-index-creation: true

  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /
